spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lmsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # මෙය production වලදී 'none' හෝ 'validate' ලෙස වෙනස් කළ යුතුය
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # ඔබගේ JWT issuer URL එකට ගැලපෙන ලෙස වෙනස් කරන්න

server:
  port: 8080

jwt:
  secret: AVeryVerySecretKeyForJWTTokensThatIsLongEnoughAndSecure 
  expirationMs: 86400000 # 24 hours in milliseconds (24 * 60 * 60 * 1000)

cors:
  allowedOrigins: "http://localhost:3000" # React frontend URL එක